[package]
name = "dataset-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# systemstat = "0.2.2"
sysinfo = "0.27.1"